language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - prototype/elm-stuff/build-artifacts
before_script:
  - cd prototype
  - npm install -g elm@0.16 elm-test
  - ./travis-elm-install-wrapper.sh
script: make app
