language: node_js
node_js:
  - "0.12"
# https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html
# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - prototype/elm-stuff/build-artifacts
before_script:
  - cd prototype
  - npm install -g elm@0.16 elm-test
  - ./travis-elm-install-wrapper.sh
script: make app
