
docs:
	elm make --docs=documentation.json
	@echo now upload documentation.json to http://package.elm-lang.org/help/docs-preview

ngrok:
	ngrok http 8088

app:
	elm make src/App.elm --output swipe-local-history.js

